version: '3.9'

services:
  geekconsole:
    container_name: geekconsole-develop
    build:
      context: .
      target: gc
      dockerfile: ./Dockerfile_gitlab
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3000:3000
