---
  name: Build-Promote-GitOps
  
  on:
    push:
      branches:
        - main
        - devops
      paths-ignore:
        - 'README.md'
        - '.github/linters/**'
    pull_request:
      paths-ignore:
        - 'README.md'
        - '.github/linters/**'
  
  concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}
    cancel-in-progress: true
  
  jobs:
  
  #### PULL REQUEST ####
    docker-build-pr:
      name: Call Build on PR
      if: github.event_name == 'pull_request'
      permissions:
        contents: read
        packages: write
        pull-requests: write
      uses: devcraftftw/actions/.github/workflows/reusable-docker-build.yml@main
      with:
        # DON'T login to or push to Docker Hub
        dockerhub-enable: false
        ghcr-enable: true
        push: true
        # platforms: linux/amd64,linux/arm64
        platforms: linux/amd64
        context: "{{defaultContext}}"
        file: "./Dockerfile_dev"
        target: "gc"
        tag-rules: |
          type=ref,event=tag,priority=200
          type=raw,value=gha-${{ github.run_id }},enable=${{github.event_name == 'pull_request'}},priority=200
          type=ref,event=pr,priority=100
        image-names: |
          ghcr.io/${{ github.repository }}
  #### TRIVY SCAN ####
    scan:
      name: Scan Image
      needs: [docker-build-pr]
      uses: devcraftftw/actions/.github/workflows/reusable-trivy.yml@main
      with:
        image: 'ghcr.io/devcraftftw/geekconsole:${{ needs.call-docker-build.outputs.image-tag }}'
  
  #### MERGE TO MAIN ####
    docker-build-merge:
      name: Call Build on Push
      if: github.event_name == 'push'
      permissions:
        contents: read
        packages: write
        pull-requests: write
      uses: devcraftftw/actions/.github/workflows/reusable-docker-build.yml@main
      with:  
        dockerhub-enable: false
        ghcr-enable: true
        push: true
        # platforms: linux/amd64,linux/arm64
        platforms: linux/amd64
        context: "{{defaultContext}}"
        file: "./Dockerfile_dev"
        target: "gc"
        tag-rules: |
          type=raw,value={{date 'YYYYMMDD'}}-{{sha}},enable=true,priority=300
          type=ref,event=tag,priority=200
        image-names: |
          ghcr.io/${{ github.repository }}-stable
  
    gitops-pr:
      permissions: write-all
      name: Call GitOps PR
      if: github.event_name == 'push'
      needs: docker-build-merge
      uses: devcraftftw/actions/.github/workflows/reusable-gitops-pr.yml@main
      secrets:
        github-token: ${{ secrets.GITOPS_GEEKCONSOLE_K8S }}
        slack-token: ${{ secrets.SLACK_BOT_TOKEN }}
      with:
        repo: devcraftftw/geekconsole-k8s
        kustomize-path: environments/production
        slack-channel-id: 'C06EGE88BAQ'
        image: ghcr.io/${{ github.repository }}-stable
        tag: ${{ needs.docker-build-merge.outputs.image-tag }}